### ISSUE TITLE
Selecting lock or unlock slave from Xbox HD E:\eeprom.bin not working

### ISSUE THREAD

**Issue by Lord-Raziel** [Rocky5/Chimp261812#1]
Hi Rocky5,

I'm using Chimp261812, I'm trying to lock an hdd that I accidentally unlocked by using an old version of Chimp, I have copied eeprom.bin (all in lowercase) at root E: but when I use the Lock option number 3 (option 3 is highlighted in the Lock Slave menu, then I press button A on the original xbox controller) and the next screen shows information about Locking from Motherboard, I have an screenshot of the hd key that is contained in the E:\eeprom.bin and does not correspond, is reading all the time the option 1 (Lock from Motherboard), this also occurs when unlocking the slave hdd, the from Xbox HD E:\eeprom.bin is not working, it uses the motherboard key.

If you need more info or screenshots please let me know, my email address is eduardo.quintero@gmail.com

Regards,
Eduardo Q

**Comment by Rocky5** [comment]
That's because Linux on the Xbox, fatx mounting driver isn't the greatest, the cloning is done via dd and doesn't require mounting of partitions. 

Basically if your E partition has lots of folders/files it doesn't show them all when mounting E.
